### ISSUE TITLE
Errore di posizionamento di due immagini

### ISSUE THREAD

**Issue by nicolasalberti00** [FedeBrichi/Reti#2]
Buonasera, non avendo la vostra mail vi contatto qui, dicendovi che ho notato che a pagina 58 del vostro PDF (che attualmente sto usando per studiare e vi ringrazio infinitamente di quello che avete fatto perchè è un grandissimo lavoro) c'è un piccolo errore di posizionamento delle immagini: so che è una sciocchezza, ma a prima vista mette un pochino in confusione, perchè le due immagini si riferiscono agli argomenti opposti (la prima al problema della stazione esposta, la seconda al problema della stazione nascosta quando dovrebbe essere viceversa).
Vi ringrazio ancora dell'incredibile lavoro e mi scuso per il disturbo. 
Nicolas

**Comment by ARDbones** [comment]
Ciao Nicolas, grazie per la segnalazione. Ho corretto le due immagini, senza rigenerare il pdf non avendo più il compilatore Latex sul pc.
Se dovessi notare altri errori puoi sistemarli e fare una pull request, così verrai anche inserito nei contributors.
Buona fortuna per l'esame!

**Comment by nicolasalberti00** [comment]
Va benissimo, grazie ancora e buona giornata!
Il 3 apr 2021, 14:58 +0200, Riccardo ***@***.***>, ha scritto:
